coverage:
  status:
    default_rules:
    project:
      default:
        target: auto
        threshold: 1%
        flags:
          - Cpp
          - ReactJS
codecov:
  notify:
    after_n_builds: 2
comment:
  after_n_builds: 2
